name: Formula checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - run: python3 -m unittest discover -s tests -v
      - run: git diff --check
  brew:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: Homebrew/actions/setup-homebrew@9f17989bd508c794353d974d1756f23b0bcf10c1 # main
      - name: Install and test khsier
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          brew tap zaubermaerchen/tap
          cp Formula/khsier.rb "$(brew --repository zaubermaerchen/tap)/Formula/khsier.rb"
          brew install zaubermaerchen/tap/khsier
          brew test zaubermaerchen/tap/khsier
